### ISSUE TITLE
[QUESTION]:

### ISSUE THREAD

**Issue by jitengfei** [milvus-io/pymilvus#2591]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What is your question?

milvus version 2.4.12
pymilvus version 2.5.4

When I used AsyncMilvusClient in FastAPI, I encountered the following error:
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "d:\projects\test\milvus_test\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "d:\projects\test\milvus_test\env\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "d:\projects\test\milvus_test\env\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "d:\projects\test\milvus_test\env\lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "d:\projects\test\milvus_test\env\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__    
    raise exc
  File "d:\projects\test\milvus_test\env\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__    
    await self.app(scope, receive, _send)
  File "d:\projects\test\milvus_test\env\lib\site-packages\starlette\middleware\gzip.py", line 20, in __call__       
    await responder(scope, receive, send)
  File "d:\projects\test\milvus_test\env\lib\site-packages\starlette\middleware\gzip.py", line 39, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "d:\projects\test\milvus_test\env\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "d:\projects\test\milvus_test\env\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "d:\projects\test\milvus_test\env\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "d:\projects\test\milvus_test\env\lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "d:\projects\test\milvus_test\env\lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "d:\projects\test\milvus_test\env\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "d:\projects\test\milvus_test\env\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "d:\projects\test\milvus_test\env\lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "d:\projects\test\milvus_test\env\lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "d:\projects\test\milvus_test\env\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "d:\projects\test\milvus_test\env\lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "d:\projects\test\milvus_test\env\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\projects\test\milvus_test\controller\test.py", line 16, in search
    result = await get_bing_web_search_cache(q="")
  File "D:\projects\test\milvus_test\core\milvus_test.py", line 22, in get_bing_web_search_cache
    res = await client.search(
  File "d:\projects\test\milvus_test\env\lib\site-packages\pymilvus\milvus_client\async_milvus_client.py", line 394, in search
    raise ex from ex
  File "d:\projects\test\milvus_test\env\lib\site-packages\pymilvus\milvus_client\async_milvus_client.py", line 379, in search
    res = await conn.search(
  File "d:\projects\test\milvus_test\env\lib\site-packages\pymilvus\client\async_grpc_handler.py", line 600, in search
    return await self._execute_search(request, timeout, round_decimal=round_decimal, **kwargs)
  File "d:\projects\test\milvus_test\env\lib\site-packages\pymilvus\client\async_grpc_handler.py", line 548, in _execute_search
    raise e from e
  File "d:\projects\test\milvus_test\env\lib\site-packages\pymilvus\client\async_grpc_handler.py", line 538, in _execute_search
    response = await self._async_stub.Search(request, timeout=timeout)
  File "d:\projects\test\milvus_test\env\lib\site-packages\grpc\aio\_interceptor.py", line 471, in __await__
    call = yield from self._interceptors_task.__await__()
RuntimeError: Task <Task pending name='Task-12' coro=<RequestResponseCycle.run_asgi() running at d:\projects\test\milvus_test\env\lib\site-packages\uvicorn\protocols\http\h11_impl.py:406> cb=[set.discard()]> got Future <Task pending name='Task-13' coro=<InterceptedUnaryUnaryCall._invoke() running at d:\projects\test\milvus_test\env\lib\site-packages\grpc\aio\_interceptor.py:652> cb=[InterceptedCall._fire_or_add_pending_done_callbacks()]> attached to a different loop

**Comment by jitengfei** [comment]
fastapi==0.115.0
uvicorn==0.31.0
pymilvus[midel]==2.5.4

**Comment by XuanYang-cn** [comment]
/assign @brcarry 
PTAL

**Comment by brcarry** [comment]
@jitengfei Could you show me how you use the AsyncMilvusClient in your code?

**Comment by liubaiand** [comment]
通过这个调fastapi CMD ["gunicorn", "main:app", "-k", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:9088","--workers", "4","--threads","2","--timeout","2000","--capture-output"] 
代码中正常使用 AsyncMilvusClient
@brcarry

**Comment by liubaiand** [comment]
@jitengfei May I ask if the issue has been resolved?

**Comment by ahmadcolourbox** [comment]
A workaround is to use send it to `to_thread`:


```python
    async def async_search(self, **kwargs):
        def run_sync_search():
            self.client.load_collection(kwargs.get('collection_name'))
            return self.client.search(**kwargs)

        result = await asyncio.to_thread(run_sync_search)

        return result
```

**Comment by iamcodingcat** [comment]
I encountered this error with async api in `fastapi + uvicorn + gunicorn`.(pymilvus version `2.5.8`)
@ahmadcolourbox I try to your code snippet but in my case, `result` variable is still coroutine object. How to get data from coroutine object in your code snippet?

**Comment by ahmadcolourbox** [comment]
@iamcodingcat Yes, just use the sync library not the async.

A better approach is to use decorators:
```python
def make_async(func: Callable) -> Any:
    @functools.wraps(func)
    async def async_wrapper(*args, **kwargs) -> Any:
        return await asyncio.to_thread(functools.partial(func, *args, **kwargs))
    return async_wrapper
```

And then in your client file that connect to Milvus create a search function and wrap it up with the `make_async` decorator:

```python
@make_async
def async_search(self, **kwargs):
    return self.client.search(**kwargs)
```

From FastAPI:

```python
results = await async_search(...)
```

**Comment by iamcodingcat** [comment]
@ahmadcolourbox really thanks for your detailed guide! I succeed in pymilvus sync + asyncio due to your code snippet.
And a milvus developer(already thanks for @XuanYang-cn) is assigned to this issue yesterday :)

**Comment by XuanYang-cn** [comment]
I'm looking into it right now.

But beware, async_milvus_client is still in EXPERIMENTAL state, it lakes a lot of apis. Please try to use the sync search before this is fixed

**Comment by muazhari** [comment]
I still have this problem with  `pymilvus==2.6.0`. 
Please fix it.

Logs:
```python
RuntimeError: Task <Task pending name='Task-238' coro=<main() running at /mnt/c/data/apps/social-media-rag/app.py:294>> got Future <Task pending name='Task-265' coro=<InterceptedUnaryUnaryCall._invoke() running at /mnt/c/data/apps/social-media-rag/.venv/lib/python3.13/site-packages/grpc/aio/_interceptor.py:652> cb=[InterceptedCall._fire_or_add_pending_done_callbacks()]> attached to a different loop
File "/mnt/c/data/apps/social-media-rag/.venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 128, in exec_func_with_error_handling result = func() File "/mnt/c/data/apps/social-media-rag/.venv/lib/python3.13/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 669, in code_to_exec exec(code, module.dict) # noqa: S102 ~~~~^^^^^^^^^^^^^^^^^^^^^^^ File "/mnt/c/data/apps/social-media-rag/app.py", line 315, in <module> asyncio.run(main()) ~~~~~~~~~~~^^^^^^^^ File "/mnt/c/data/apps/social-media-rag/.venv/lib/python3.13/site-packages/nest_asyncio.py", line 30, in run return loop.run_until_complete(task) ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^ File "/mnt/c/data/apps/social-media-rag/.venv/lib/python3.13/site-packages/nest_asyncio.py", line 98, in run_until_complete return f.result() ~~~~~~~~^^ File "/home/muazhari/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/asyncio/futures.py", line 199, in result raise self._exception.with_traceback(self._exception_tb) File "/home/muazhari/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/asyncio/tasks.py", line 306, in __step_run_and_handle_result result = coro.throw(exc) File "/mnt/c/data/apps/social-media-rag/app.py", line 294, in main result = await query_use_case.execute(query) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/mnt/c/data/apps/social-media-rag/internals/use_cases/query_use_case.py", line 30, in execute retrieved: List[Tuple[LCDocument, float]] = await self.vector_store.asimilarity_search_with_score( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ...<2 lines>... ) ^ File "/mnt/c/data/apps/social-media-rag/internals/customs/milvus/milvus.py", line 2731, in asimilarity_search_with_score col_search_res = await self._acollection_search( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ...<6 lines>... ) ^ File "/mnt/c/data/apps/social-media-rag/internals/customs/milvus/milvus.py", line 2510, in _acollection_search col_search_res = await self.aclient.search( ^^^^^^^^^^^^^^^^^^^^^^^^^^ ...<9 lines>... ) ^ File "/mnt/c/data/apps/social-media-rag/.venv/lib/python3.13/site-packages/pymilvus/milvus_client/async_milvus_client.py", line 440, in search raise ex from ex File "/mnt/c/data/apps/social-media-rag/.venv/lib/python3.13/site-packages/pymilvus/milvus_client/async_milvus_client.py", line 425, in search res = await conn.search( ^^^^^^^^^^^^^^^^^^ ...<11 lines>... ) ^ File "/mnt/c/data/apps/social-media-rag/.venv/lib/python3.13/site-packages/pymilvus/client/async_grpc_handler.py", line 774, in search return await self._execute_search(request, timeout, round_decimal=round_decimal, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/mnt/c/data/apps/social-media-rag/.venv/lib/python3.13/site-packages/pymilvus/client/async_grpc_handler.py", line 712, in _execute_search response = await self._async_stub.Search( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ request, timeout=timeout, metadata=_api_level_md(**kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ) ^ File "/mnt/c/data/apps/social-media-rag/.venv/lib/python3.13/site-packages/grpc/aio/_interceptor.py", line 471, in await call = yield from self._interceptors_task.await() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/muazhari/.local/share/uv/python/cpython-3.13.2-linux-x86_64-gnu/lib/python3.13/asyncio/futures.py", line 286, in await yield self # This tells Task to wait for completion. ^^^^^^^^^^</module>
```

**Comment by lanshee** [comment]
pymilvus==2.6.0
I'm having the same issue here. This does seem like a serious problem, so could you please look into resolving it as soon as you can?
logs:
```
Traceback (most recent call last):
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\opentelemetry\instrumentation\asgi\__init__.py", line 745, in __call__
    await self.app(scope, otel_receive, otel_send)
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\starlette\middleware\base.py", line 176, in __call__
    with recv_stream, send_stream, collapse_excgroups():
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\starlette\_utils.py", line 82, in collapse_excgroups
    raise exc
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\starlette\middleware\base.py", line 178, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\files\pycharmProject\smart_search\app\middlewares\mysql.py", line 12, in db_session_middleware
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\starlette\middleware\base.py", line 156, in call_next
    raise app_exc
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\starlette\middleware\base.py", line 141, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\files\pycharmProject\smart_search\app\apis\milvus\views.py", line 185, in search_video
    raw_results = await raw_results
                  ^^^^^^^^^^^^^^^^^
  File "D:\files\pycharmProject\smart_search\app\apis\milvus\milvus_helpers.py", line 364, in mm_search
    results = await self.mc.search(
              ^^^^^^^^^^^^^^^^^^^^^
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\pymilvus\milvus_client\async_milvus_client.py", line 440, in search
    raise ex from ex
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\pymilvus\milvus_client\async_milvus_client.py", line 425, in search
    res = await conn.search(
          ^^^^^^^^^^^^^^^^^^
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\pymilvus\client\async_grpc_handler.py", line 750, in search
    await self.ensure_channel_ready()
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\pymilvus\client\async_grpc_handler.py", line 241, in ensure_channel_ready
    raise e from e
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\pymilvus\client\async_grpc_handler.py", line 222, in ensure_channel_ready
    await self._async_channel.channel_ready()
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\grpc\aio\_channel.py", line 481, in channel_ready
    await self.wait_for_state_change(state)
  File "D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\grpc\aio\_channel.py", line 474, in wait_for_state_change
    assert await self._channel.watch_connectivity_state(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src\\python\\grpcio\\grpc\\_cython\\_cygrpc/aio/channel.pyx.pxi", line 97, in watch_connectivity_state
RuntimeError: Task <Task pending name='starlette.middleware.base.BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.coro' coro=<BaseHTTPMiddleware.__call__.<locals>.call_next.<locals>.coro() running at D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\starlette\middleware\base.py:141> cb=[TaskGroup._spawn.<locals>.task_done() at D:\files\.pyenv\pyenv-win\versions\3.12.2\Lib\site-packages\anyio\_backends\_asyncio.py:794]> got Future <Future pending> attached to a different loop
```

**Comment by diffraction-zebra** [comment]
It’s enough to move the client initialization to the FastAPI lifespan.

The problem is that the Milvus client actually creates the connection asynchronously during __init__ and tries to wait for it to complete in a different event loop during requests. If you place it in the lifespan, the connection will be created in the same event loop that was created by Uvicorn.

```python
client: AsyncMilvusClient | None = None

@asynccontextmanager
async def lifespan(app: FastAPI):
    client = AsyncMilvusClient(uri="http://localhost:19530")
    try:
        yield
    finally:
        ...

app = FastAPI(lifespan=lifespan)
```

**Comment by ichiyan** [comment]
> I'm looking into it right now.
> 
> But beware, async_milvus_client is still in EXPERIMENTAL state, it lakes a lot of apis. Please try to use the sync search before this is fixed

Is AsyncMilvusClient still experimental and not recommended to be used in production?
